services:
  db:
    image: postgres:17
    container_name: ecommerce_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: ecommerce_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: ecommerce_backend
    environment:
      - DB_USERNAME=postgres
      - DB_PASSWORD=root
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/ecommerce_db
    ports:
      - '8080:8080'
    depends_on:
      - db

  pgadmin:
    image: dpage/pgadmin4
    container_name: ecommerce_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - '5050:80'
    depends_on:
      - db
volumes:
  postgres_data:
